app/its/forms.py
# app/admin/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, DateTimeField, RadioField, validators,DateField, SelectField
from wtforms.validators import DataRequired
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from ..models import Department
from datetime import datetime

import time

class DepartmentForm(FlaskForm):
    """
    Form for admin to add or edit a department
    """
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description',)
    submit = SubmitField('Submit')

class EquipmentForm(FlaskForm):
    """
    Form for admin to add or edit a equipment
    """
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description')
    serialnumber = StringField('Serial Number')
    modelnumber = StringField('Model Number')
    location = StringField('Location')
    status = StringField('Status')
    type = RadioField('Type', choices=[('Amplifier','Amplifier'),('Encoder','Encoder'),('Camera','Camera'),
                                       ('Receiver','Receiver'),('Other','Other')],validators=[validators.DataRequired()])
    submit = SubmitField('Submit')


class EmployeeAssignForm(FlaskForm):
    """
    Form for admin to assign departments and roles to employees
    """
    department = QuerySelectField(query_factory=lambda: Department.query.all(),
                                  get_label="name")
    submit = SubmitField('Submit')

class ReportsForm(FlaskForm):

    date = StringField('Date',render_kw={"placeholder": "2016-09-26"},validators=[validators.DataRequired()])
    company = StringField('Client')
    service_provided = StringField('Service Provided')
    location = StringField('Location')
    space = StringField('Space')
    time_gmt_s = StringField('S Time GMT')
    time_gmt_e = StringField('E Time GMT')
    extension = StringField('Extension')
    actual_s_time = StringField('Actual S Time')
    actual_e_time = StringField('Actual E Time')
    duration = StringField('Duration')
    engineer = StringField('Engineer')
    reference = StringField('Reference No.')
    guest = StringField('Guest')
    transport_company = StringField('Transport Company')
    transport_kind = StringField('Transport Kind')
    note = StringField('Note')
    extrafees = StringField('Extra Fees')
    type = RadioField('Type', choices=[('Office','Office'),('SNG','SNG'),('ENG','ENG')])
    submit = SubmitField('Submit')


class LivesForm(FlaskForm):

    date = DateField('Date',format="%Y-%m-%d", default=datetime.today,validators=[validators.DataRequired()])
    company = StringField('Client')
    service_provided = StringField('Service Provided')
    sat = StringField('Satellite info')
    ul = StringField('Uplink')
    dl = StringField('Downlink')
    sr = StringField('Symbol Rate')
    fec = StringField('FEC')
    mod = StringField('Modulation')
    access = StringField('Sat Access')
    reference = StringField('Reference')
    time_gmt_s = StringField('S Time GMT')
    time_gmt_e = StringField('E Time GMT')
    reg_code = StringField('Reg Code')
    location = RadioField('Type', choices=[('Maspero','Maspero'),('Agoza','Agoza'),('Street','Street')])
    submit = SubmitField('Submit')

class FreelancersForm(FlaskForm):

    job = RadioField('Job', choices=[('Camera Man','Camera Man'),('Sound Engineer','Sound Engineer'),('Assistant','Assistant'),('Other','Other')])
    first_name = StringField('First Name')
    last_name = StringField('Last Name')
    hire_rate = StringField('Hiring Rate')
    tel = StringField('Telephone No.')
    submit = SubmitField('Submit')


class TransportsForm(FlaskForm):

    date = StringField('Date',render_kw={"placeholder": "2016-09-26"},validators=[validators.DataRequired()])
    company = StringField('Client')
    reference = StringField('Reference')
    guest_counter = SelectField(
        'Number of Guests',
        choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')])
    guest1 = StringField('Guest1')
    city1 = StringField('City1')

    guest2 = StringField('Guest2')
    city2 = StringField('City2')

    guest3 = StringField('Guest3')
    city3 = StringField('City3')

    guest4 = StringField('Guest4')
    city4 = StringField('City4')

    guest5 = StringField('Guest5')
    city5 = StringField('City5')

    guest6 = StringField('Guest6')
    city6 = StringField('City6')

    guest7 = StringField('Guest7')
    city7 = StringField('City7')

    guest8 = StringField('Guest8')
    city8 = StringField('City8')

    guest9 = StringField('Guest9')
    city9 = StringField('City9')

    guest10 = StringField('Guest10')
    city10 = StringField('City10')

    note = StringField('Note')
    submit = SubmitField('Submit')

class StudiosForm(FlaskForm):
    showname = SelectField('Show Name', choices=[('Al Youm', 'Al Youm'), ('Best of Al Youm', 'Best of Al Youm'),
                                                ('Kalam Masry', 'Kalam Masry'),
                                                ('Dispute or Differences', 'Dispute or Differences'),
                                                ('Other', 'Other')])
    date = StringField('Date',render_kw={"placeholder": "2016-09-26"},validators=[validators.DataRequired()])
    company = StringField('Client')
    reference = StringField('Reference No.')
    time_gmt_s = StringField('S Time GMT')
    time_gmt_e = StringField('E Time GMT')
    guest_counter = SelectField(
        'Number of Guests',
        choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'),
                 ('9', '9'), ('10', '10')])
    guest1 = StringField('Guest1')
    guest2 = StringField('Guest2')
    guest3 = StringField('Guest3')
    guest4 = StringField('Guest4')
    guest5 = StringField('Guest5')
    guest6 = StringField('Guest6')
    guest7 = StringField('Guest7')
    guest8 = StringField('Guest8')
    guest9 = StringField('Guest9')
    guest10 = StringField('Guest10')

    note = StringField('Note')
    submit = SubmitField('Submit')

class NotesForm(FlaskForm):
    """
    Form to add or edit a lives
    """

    note = StringField('Note')
    actual_s_time = StringField('Actual S')
    actual_e_time = StringField('Actual E')
    submit = SubmitField('Submit')


class SngordersForm(FlaskForm):

    date = StringField('Date',render_kw={"placeholder": "2016-09-26"},validators=[validators.DataRequired()])
    company = StringField('Client')
    engineer = StringField('Engineer')
    location = StringField('Location')
    reference = StringField('Reference No.')
    time_gmt_s = StringField('S Time GMT')
    time_gmt_e = StringField('E Time GMT')
    cameraman = StringField('Camera Man')
    tech = StringField('Technician')
    driver = StringField('Driver')
    camera = StringField('Camera')
    car = StringField('Car')
    note = StringField('Note')
    submit = SubmitField('Submit')


class GuestsForm(FlaskForm):

    job = StringField('Job')
    title = StringField('Title')
    first_name = StringField('First Name')
    last_name = StringField('Last Name')
    tel = StringField('Telephone No.')
    address = StringField('Address')
    submit = SubmitField('Submit')

app/its/__init__.py
# app/admin/__init__.py

from flask import Blueprint

its = Blueprint('its', __name__)

from . import views

app/its/views.py
from flask import abort, flash, redirect, render_template, url_for, request
from flask_login import current_user, login_required
from forms import DepartmentForm, EmployeeAssignForm ,EquipmentForm, ReportsForm, LivesForm, FreelancersForm, TransportsForm, StudiosForm, NotesForm, SngordersForm, GuestsForm
from ..models import Department, Employee, Equipment, Reports, Lives, Freelancers, Transports, Studios, Sngorders, Guests
from . import its
from .. import db
from datetime import datetime
import flask_excel as excel
import pyexcel.ext.xls, pyexcel.ext.xlsx



now = datetime.now().strftime("%Y-%m-%d")
def check_admin():
    """
    Prevent non-admins from accessing the page
    """
    if not current_user.is_admin:
        abort(403)

def check_heng():
    """
    prevent non-heng from accessing this page
    """
    if not current_user.is_heng:
        abort(403)

def check_acc():
    """
    prevent non-acc from accessing this page
    """
    if not current_user.is_acc:
        abort(403)


# Department Views

@its.route('/departments', methods=['GET', 'POST'])
@login_required
def list_departments():
    """
    List all departments
    """
    departments = Department.query.order_by(Department.name)

    return render_template('its/departments/departments.html',
                            departments=departments, title="Departments")



@its.route('/departments/add', methods=['GET', 'POST'])
@login_required
def add_department():
    """
    Add a department to the database
    """
    if current_user.is_admin == True or current_user.is_acc == True:

        add_department = True

        form = DepartmentForm()
        if form.validate_on_submit():
            department = Department(name=form.name.data,
                                description=form.description.data)
            try:
                # add department to the database
                db.session.add(department)
                db.session.commit()
                flash('You have successfully added a new department.')
            except:
                # in case department name already exists
                flash('Error: department name already exists.')

            # redirect to departments page
            return redirect(url_for('its.list_departments'))

        # load department template
        return render_template('its/departments/department.html', action="Add",
                            add_department=add_department, form=form,
                            title="Add Department")
    else:
        abort(403)


#Edit Departments

@its.route('/departments/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_department(id):
    """
    Edit a department
    """
    if current_user.is_admin == True or current_user.is_acc == True:

        add_department = False

        department = Department.query.get_or_404(id)
        form = DepartmentForm(obj=department)
        if form.validate_on_submit():
            department.name = form.name.data
            department.description = form.description.data
            db.session.commit()
            flash('You have successfully edited the department.')

            # redirect to the departments page
            return redirect(url_for('its.list_departments'))

        form.description.data = department.description
        form.name.data = department.name
        return render_template('its/departments/department.html', action="Edit",
                            add_department=add_department, form=form,
                            department=department, title="Edit Department")
    else:
        abort(403)

#Delete Department

@its.route('/departments/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_department(id):
    """
    Delete a department from the database
    """
    if current_user.is_admin == True or current_user.is_acc == True:

        department = Department.query.get_or_404(id)
        db.session.delete(department)
        db.session.commit()
        flash('You have successfully deleted the department.')

        # redirect to the departments page
        return redirect(url_for('its.list_departments'))

        return render_template(title="Delete Department")
    else:
        abort(403)

@its.route('/departments/sub/<int:id>', methods=['GET', 'POST'])
@login_required
def list_employees_dep(id):
    """
    List sub departments
    """

    employees = Employee.query.filter(Employee.department_id==id).order_by(Employee.first_name)
    return render_template('its/departments/sub.html',Department=Department,
                        employees=employees, title='Employees')


# Employee Views
@its.route('/employees')
@login_required
def list_employees():

    employees = Employee.query.filter(Employee.first_name!=None).order_by(Employee.department_id)
    return render_template('its/employees/employees.html',
                        employees=employees, title='Employees')



@its.route('/employees/assign/<int:id>', methods=['GET', 'POST'])
@login_required
def assign_employee(id):
    """
    Assign a department and a role to an employee
    """
    if current_user.is_admin == True or current_user.is_acc == True:

        employee = Employee.query.get_or_404(id)

        # prevent admin from being assigned a department or role
        if employee.is_admin:
            abort(403)

        form = EmployeeAssignForm(obj=employee)
        if form.validate_on_submit():
            employee.department = form.department.data
            db.session.add(employee)
            db.session.commit()
            flash('You have successfully assigned a department .')

            # redirect to the roles page
            return redirect(url_for('its.list_employees'))

        return render_template('its/employees/employee.html',
                            employee=employee, form=form,
                            title='Assign Employee')
    else:
        abort(403)


@its.route('/employees/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_employee(id):
    """
    Delete a employees from the database
    """
    if current_user.is_admin == True or current_user.is_acc == True:

        employee = Employee.query.get_or_404(id)
        db.session.delete(employee)
        db.session.commit()
        flash('You have successfully deleted the employee.')

        # redirect to the departments page
        return redirect(url_for('its.list_employees'))

        return render_template(title="Delete Employee")
    else:
        abort(403)
# Equipment Views

@its.route('/equipment', methods=['GET', 'POST'])
@login_required
def list_equipment():
    """
    List all equipment
    """
    #check_admin()

    equipment = Equipment.query.order_by(Equipment.type)

    return render_template('its/equipment/equipments.html',
                           equipment=equipment, title="Equipment")
# Equipment Add

@its.route('/equipment/add', methods=['GET', 'POST'])
@login_required
def add_equipment():
    """
    Add a equipment to the database
    """
    if current_user.is_admin==True or current_user.is_heng==True:

        add_equipment = True

        form = EquipmentForm()
        if form.validate_on_submit():
            equipment = Equipment(name=form.name.data,description=form.description.data, serialnumber=form.serialnumber.data,
                                  modelnumber=form.modelnumber.data, location=form.location.data, status=form.status.data, type=form.type.data)
            # add equipment to the database
            db.session.add(equipment)
            db.session.commit()
            flash('You have successfully added a new equipment.')

            return redirect(url_for('its.list_equipment'))

        # load equipment template
        return render_template('its/equipment/equipment.html', action="Add",
                            add_equipment=add_equipment, form=form,
                            title="Add Equipment")
    else:
        abort(403)


# Equipment Edit

@its.route('/equipment/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_equipment(id):
    """
    Edit a equipment
    """
    if current_user.is_admin == True or current_user.is_heng == True:

        add_equipment = False

        equipment = Equipment.query.get_or_404(id)
        form = EquipmentForm(obj=equipment)
        if form.validate_on_submit():
            equipment.name = form.name.data
            equipment.description = form.description.data
            equipment.serialnumber = form.serialnumber.data
            equipment.modelnumber = form.modelnumber.data
            equipment.location = form.location.data
            equipment.status = form.status.data
            equipment.type = form.type.data
            db.session.commit()
            flash('You have successfully edited the equipment.')

            # redirect to the equipment page
            return redirect(url_for('its.list_equipment'))

        form.name.data = equipment.name
        form.description.data = equipment.description
        form.serialnumber.data = equipment.serialnumber
        form.modelnumber.data = equipment.modelnumber
        form.location.data = equipment.location
        form.status.data = equipment.status
        form.type.data = equipment.type
        return render_template('its/equipment/equipment.html', action="Edit",
                            add_equipment=add_equipment, form=form,
                            equipment=equipment, title="Edit Equipment")
    else:
        abort(403)
# Equipment Delete

@its.route('/equipment/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_equipment(id):
    """
    Delete a equipment from the database
    """
    if current_user.is_admin == True or current_user.is_heng == True:

        equipment = Equipment.query.get_or_404(id)
        db.session.delete(equipment)
        db.session.commit()
        flash('You have successfully deleted the equipment.')

        # redirect to the equipment page

app/templates/its/employees/employee.html
<!-- app/templates/admin/employees/employee.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Assign Employee{% endblock %}
{% block body %}
<div class="mainbg">
  <div class="content-section">
      <div class="inner">
        <div class="center">
            <h1> Assign Departments </h1>
            <br/>
            <p>
                Select a department  to assign to
                <span style="color: #aec251;">
                    {{ employee.first_name }} {{ employee.last_name }}
                </span>
            </p>
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
  </div>
</div>
{% endblock %}

app/templates/its/employees/employees.html
<!-- app/templates/admin/employees/employees.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Employees{% endblock %}
{% block body %}
<div class="mainbg">
  <div class="content-section">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 class='spacyan' style="text-align:center;">Employees</h1>
        {% if employees %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> Name </th>
                  <th width="30%"> Department </th>
                  <th width="20%"> Hire Date</th>
                {% if current_user.is_admin or current_user.is_acc %}
                  <th width="15%"> Salary </th>
                {% endif %}
                  <th width="20%"> Telephone No.</th>
                  <th width="15%"> Assign Department </th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for employee in employees %}
                {% if employee.is_admin %}
                    <tr style="background-color: #aec251; color: white;">
                        <td> <i class="fa fa-key"></i> Admin </td>
                        <td> N/A </td>
                        <td> N/A </td>
                        <td> N/A </td>
                        <td> N/A </td>
                    </tr>
                {% else %}
                    <tr>
                      <td> {{ employee.first_name }} {{ employee.last_name }} </td>
                      <td>
                        {% if employee.department %}
                          {{ employee.department.name }}
                        {% else %}
                          -
                        {% endif %}
                      </td>
                      <td>
                        {{  employee.hire_date  }}
                      </td>
                    {% if current_user.is_admin or current_user.is_acc %}
                      <td>
                        {{ employee.salary  }}
                      </td>
                    {% endif %}
                      <td>
                        {{ employee.tel  }}
                      </td>
                      <td>
                        <a href="{{ url_for('its.assign_employee', id=employee.id) }}">
                          <i class="fa fa-user-plus"></i> Assign Department
                        </a>
                      </td>
                      <td>
                        <a style="color:green;" href="{{ url_for('auth.edit_employee', id=employee.id) }}">
                          <i class="fa fa-user-plus"></i> Edit
                        </a>
                      </td>
                      <td>
                        <a style="color:red;" href="{{ url_for('its.delete_employee', id=employee.id) }}">
                          <i class="fa fa-user-plus"></i> Delete
                        </a>
                      </td>
                    </tr>
                {% endif %}
              {% endfor %}
              </tbody>
            </table>
          </div>
         <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3 style="text-align: center"> No employees have been added yet. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('auth.register') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Employee
          </a>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}